### ISSUE TITLE
Are Field types immutable?

### ISSUE THREAD

**Issue by JamesTreleaven** [streamsets/tutorials#109]
I've built a working 'streamsets destination' to feed data into the analytics platform my team is working on, but I have a question about 'schema'.

With respect to the 'field type' (ie what is returned from Field.getType()), are these types immutable for a given fieldPath ... or might these types change over time for any single given fieldPath?

Thanks in advance.

**Comment by JamesTreleaven** [comment]
I have found a design solution such that I don't need to know the answer to this question.

**Comment by metadaddy** [comment]
Glad you figured that out, because field types can certainly change, due to the [Field Type Converter](https://streamsets.com/documentation/datacollector/latest/help/datacollector/UserGuide/Processors/FieldTypeConverter.html#concept_is3_zkp_wq).
