### ISSUE TITLE
ip address not found in geo database

### ISSUE THREAD

**Issue by linkwoman** [streamsets/tutorials#11]
Trying to do the logs to elasticsearch tutorial but get ip address not found in the geo database:

![image](https://cloud.githubusercontent.com/assets/2505005/13977627/f79fc9e4-f087-11e5-8dd5-348635bf94a1.png)

![image](https://cloud.githubusercontent.com/assets/2505005/13977676/563334be-f088-11e5-91b9-33466780f91c.png)

The mmdb is in the resources directory:
![image](https://cloud.githubusercontent.com/assets/2505005/13977706/8a4e21b4-f088-11e5-8224-24810a39b77d.png)

**Comment by linkwoman** [comment]
Thanks for the explanation but I should've mentioned that while some do not have an error, no data ends up in the elasticsearch index.   I do have it set to create the records even on preview.

**Comment by metadaddy** [comment]
Hmm - I wonder why. Does the pipeline validate ok? Do you see data in the ElasticSearch index if you run the pipeline? Do you see any errors when you click on the ElasticSearch destination? Any evidence in `/streamsets-datacollector/log/sdc.log`?

@kiritbasu Any ideas?

**Comment by kiritbasu** [comment]
Those would be the places to check. Also is the index mapping setup right? 
Which version of SDC and Elastic are you on?
