### ISSUE TITLE
Failed to instantiate class org.neo4j.driver.v1.Driver

### ISSUE THREAD

**Issue by wenzhenghu** [streamsets/tutorials#112]
> 2019-07-31 17:25:38,189 [user:*admin] [pipeline:mysql-to-neo4j/mysqltoneo4jeffdd684-b755-411f-b6b5-6d1396d8f1b4] [runner:] [thread:ProductionPipelineRunnable-mysqltoneo4jeffdd684-b755-411f-b6b5-6d1396d8f1b4-mysql-to-neo4j] [stage:] ERROR ProductionPipelineRunnable - An exception occurred while running the pipeline, com.streamsets.datacollector.runner.PipelineRuntimeException: CONTAINER_0800 - Pipeline 'mysqltoneo4jeffdd684-b755-411f-b6b5-6d1396d8f1b4' validation error : QUERY_EXECUTOR_002 - Can't open connection: JDBC_06 - Failed to initialize connection pool: java.lang.RuntimeException: Failed to instantiate class org.neo4j.driver.v1.Driver
> com.streamsets.datacollector.runner.PipelineRuntimeException: CONTAINER_0800 - Pipeline 'mysqltoneo4jeffdd684-b755-411f-b6b5-6d1396d8f1b4' validation error : QUERY_EXECUTOR_002 - Can't open connection: JDBC_06 - Failed to initialize connection pool: java.lang.RuntimeException: Failed to instantiate class org.neo4j.driver.v1.Driver
>         at com.streamsets.datacollector.execution.runner.common.ProductionPipeline.run(ProductionPipeline.java:139)
>         at com.streamsets.datacollector.execution.runner.common.ProductionPipelineRunnable.run(ProductionPipelineRunnable.java:75)
>         at com.streamsets.datacollector.execution.runner.standalone.StandaloneRunner.start(StandaloneRunner.java:704)
>         at com.streamsets.datacollector.execution.AbstractRunner.lambda$scheduleForRetries$0(AbstractRunner.java:361)
>         at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.lambda$call$0(SafeScheduledExecutorService.java:226)
>         at com.streamsets.datacollector.security.GroupsInScope.execute(GroupsInScope.java:33)
>         at com.streamsets.pipeline.lib.executor.SafeScheduledExecutorService$SafeCallable.call(SafeScheduledExecutorService.java:222)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
>         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
>         at com.streamsets.datacollector.metrics.MetricSafeScheduledExecutorService$MetricsTask.run(MetricSafeScheduledExecutorService.java:100)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> 

hi, i just want to dump mysql data input neo4j, but the jdbc query executor report this error. 
i could not find enough informaction to handle it

**Comment by wenzhenghu** [comment]
i have wathed this two video, but could not found entire config step for neo4j
https://www.youtube.com/watch?v=AaqsNtIGN2s
https://www.youtube.com/watch?v=_6zdEHmjEDI

**Comment by metadaddy** [comment]
Hi - this is not an issue with the tutorials. Please ask a question via one of our community channels: https://streamsets.com/community/
