### ISSUE TITLE
How can I use JDBC Query Consumer to query data from hive?

### ISSUE THREAD

**Issue by chenxiaoliang0901** [streamsets/tutorials#114]
I want to query hive as input source，But I don't know how to set it up.

**Comment by metadaddy** [comment]
You can either query the underlying Hadoop files with one of the HDFS origins, or use one of the JDBC origins with the Hive JDBC driver.

Feel free to ask more questions via one of the StreamSets community channels: https://streamsets.com/community - this really isn't an issue with the tutorials.
