### ISSUE TITLE
the same data format,http client processor can send data,but http client destinations throws error

### ISSUE THREAD

**Issue by qinzl1** [streamsets/tutorials#115]
destinations:
![image](https://user-images.githubusercontent.com/20242930/63088891-d1edf080-bf88-11e9-8716-29a84abf12d3.png)
![image](https://user-images.githubusercontent.com/20242930/63088915-dd411c00-bf88-11e9-9726-6cb7b63b4601.png)
![image](https://user-images.githubusercontent.com/20242930/63088926-e336fd00-bf88-11e9-8fe6-21ec101a1317.png)
processor:
![image](https://user-images.githubusercontent.com/20242930/63088953-f8ac2700-bf88-11e9-9baa-9ff58ccc5456.png)
![image](https://user-images.githubusercontent.com/20242930/63088973-0366bc00-bf89-11e9-8188-9c0a5d5e7484.png)

**Comment by metadaddy** [comment]
In the destination, you need to specify TEXT as the data format, with `/json_str` as the text field. Specifying JSON data format means that the entire record will be JSON-encoded, so it will actually send something like `{"json_str":"{\"appCode\":...}"}` when you want to just send `{"appCode":...}"}`

Alternatively, ensure that the record contains just the appCode, resourceType etc fields and choose JSON data format.

Create a request bin at https://requestbin.com/, use the request bin URL for both HTTP stages and you'll easily see any differences between the requests.

By the way - please don't create issues on the tutorial for general questions. There are plenty of ways to interact with the StreamSets community: https://streamsets.com/community
