### ISSUE TITLE
Spark executor Argument

### ISSUE THREAD

**Issue by studB** [streamsets/tutorials#119]
Hi.

Actually my issue is about 'spark executor', not 'spark transfomer tutorial'.
I can't find a suitable place for my issue(there is not spark executor tutorial...), so I use it.

I use 'spark executor' from 'CDH Spark 2.1.0 Release 1' library.

My pipeline is 'Directory -> Spark executor', simple thing. 

I installs spark in local. And I want to use this.
In other word, I want to implement 'spark-submit --master spark://localhost:7077' by using 'spark executor'. 

I put a option in Additional Spark Arguments in 'Spark-Configuration' like '--master spark://localhost:7077'.

But I get a error message as below.

Error: Unrecongnized option: --master spark://BDY:7077

How can i do for 'recongnize'.
A expression is wrong?

**Comment by metadaddy** [comment]
Please use one of the community channels to get general help - see https://streamsets.com/community
