### ISSUE TITLE
jdbc producer can not write record to mysql database when origin is  mysql binary log component

### ISSUE THREAD

**Issue by yudar1024** [streamsets/tutorials#121]
![image](https://user-images.githubusercontent.com/1061851/89251073-b9b72b80-d648-11ea-88b5-9d5fcc2a13ee.png)

I write a pipline like above.
the binary log configuration is
![image](https://user-images.githubusercontent.com/1061851/89251174-f4b95f00-d648-11ea-91cd-27540a73e41f.png)
![image](https://user-images.githubusercontent.com/1061851/89251214-0ef33d00-d649-11ea-8b04-2fb0461988c5.png)

jdbc producer configuration is
![image](https://user-images.githubusercontent.com/1061851/89251285-32b68300-d649-11ea-9b73-b62d6dfcd81a.png)
![image](https://user-images.githubusercontent.com/1061851/89251344-58438c80-d649-11ea-92d0-2135feab0620.png)

stream select configuration is
![image](https://user-images.githubusercontent.com/1061851/89251382-74dfc480-d649-11ea-8f88-8f91b8b2b3b6.png)

when i add a new record to database1,mysql binlog output 1 record, jdbc producer can see a good record, but in database2, the data doesn't insert into table.

**Comment by rushah** [comment]
The MySQL binlog origin generates a record for each transaction which is not just the row you say inserted in the table, but a lot of metadata associated with it. The doc describes this: https://streamsets.com/documentation/datacollector/latest/help//datacollector/UserGuide/Origins/MySQLBinaryLog.html
As a quick start, take a sample pipeline from here with the MySQL CDC origin and replace the destination with your JDBC destination. https://github.com/streamsets/pipeline-library/tree/master/datacollector/sample-pipelines
