### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by s0rbus** [streamsets/tutorials#13]
I've been through the tutorial from behind a corporate firewall so had to add proxy support. In case anyone else wants/needs to do this I had to:

in SampleTarget.java
import org.apache.http.HttpHost
add viaproxy line in Request.Post (before the bodyString) e.g.
.viaProxy(new HttpHost("my.proxy.host", 8080))

in sdc-security.policy
change sdc permission to my proxy host rather than requestb.in

**Comment by s0rbus** [comment]
I should have clarified, this is regarding the custom destination tutorial

**Comment by metadaddy** [comment]
Thanks - I'll add a note to the tutorial in the appropriate place!
