### ISSUE TITLE
ImportError: cannot import name 'MutableSequence' from 'collections'

### ISSUE THREAD

**Issue by QPeiran** [streamsets/tutorials#140]
Hi, I am installing streamsets 4.2.0 from PyPI:
It gives me an ImportError as shown in the title.
Seems there needs to be a minor change in the source code to be able to install on top of PYTHON 3.10.4: 
[[stackoverflow](https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections)](url)
![image](https://user-images.githubusercontent.com/14008800/169936407-bea7c8d1-affd-4ba2-8a6e-7038e240db0a.png)

**Comment by dimaspivak** [comment]
This has been fixed in version 4.3.0 of the DataOps Platform SDK for Python, which was released today.
