### ISSUE TITLE
RequestBin destination is not created.

### ISSUE THREAD

**Issue by ashish211981** [streamsets/tutorials#17]
Despite building the projects and copied the jar file to desired location custom requestbin not created.

**Comment by metadaddy** [comment]
Did you create a new RequestBin at the website: http://requestb.in?

**Comment by metadaddy** [comment]
Closing this since I haven't had a reply. Feel free to reopen if you're still having a problem, @ashish211981

**Comment by metadaddy** [comment]
Closing, since it's not clear what the problem is. Feel free to reopen, @ashish211981, if you want to provide some more detail.
