### ISSUE TITLE
stateful calculations processors ?

### ISSUE THREAD

**Issue by sumpan** [streamsets/tutorials#31]
can the streamsets on yarn streaming cluster model do stateful calculations?

Such as real-time statistics PV, UV or certain fields aggregation ?

will you give some advice and code sample ?

**Comment by metadaddy** [comment]
Hi @sumpan - no, at present, StreamSets is more oriented towards record-by-record transformations. You probably want to do stateful calculations in Spark Streaming. SDC can feed Spark Streaming with data - see this blog entry for an example: https://streamsets.com/blog/continuous-data-integration-streamsets-data-collector-spark-streaming-databricks/

BTW - we have a Google Group and Slack channel for general Q&A - see https://streamsets.com/community/

**Comment by sumpan** [comment]
thx for your reply @metadaddy 
ye , i want to do stateful calculation in spark streaming without writing a single line code
record-by-record transformations is very useful and really convenient, but not enough yet for me

"Google Group and Slack channel" in china can not work ,you know ,network is unreachable ,fuck 
any other way to talk about some questions ?

**Comment by metadaddy** [comment]
Happy to answer questions here if it's the only channel that works!

I don't know of a way to do stateful calculations without writing any code... I'll pass this on to our produce manager to see if it's in our long-term roadmap.

**Comment by metadaddy** [comment]
@sumpan How do you communicate with other open source communities? StackOverflow? IRC?

**Comment by metadaddy** [comment]
@sumpan Try emailing sdc-user+subscribe@googlegroups.com - let me know how you get on!

**Comment by sumpan** [comment]
Stratio sparta 
https://stratio.atlassian.net/wiki/display/SPARTA0x9/Introduction
how do you think about this ?
I think streamsets can also do that , user do have to write any code ,but use config 
as I know streamanalytix can do that thing(http://streamanalytix.com/)
besides .streamanalytix can translate pipeline both to storm topology or spark streaming job
so ,streamset have plan to support run pipeline in  apache storm cluster ?

**Comment by sumpan** [comment]
@metadaddy
