### ISSUE TITLE
SPARK_01 - Specified class: 'com.streamset.spark.processor.CustomTransformer' was not found in classpath

### ISSUE THREAD

**Issue by mikeamalraj** [streamsets/tutorials#37]
Hi Team,

I am trying to run the Spark Evaluator in streamset datacollector but i am getting error like "**SPARK_01 - Specified class: 'com.streamset.spark.processor.CustomTransformer' was not found in classpath"** in Spark Transformer Class argument
![streamset-image](https://cloud.githubusercontent.com/assets/22675708/22687422/d2ca3dbe-ecdc-11e6-938f-8209d2788118.png)
.

Please help me to fix.

**Comment by metadaddy** [comment]
Double check that you've followed the steps in https://github.com/streamsets/tutorials/tree/master/tutorial-spark-transformer#installing-a-spark-transformer

If it's still not working, please post:

- The location of your external library file directory
- The path to your `spark-transformer-example-1.0-SNAPSHOT.jar` file under that directory
- The `export STREAMSETS_LIBRARIES_EXTRA_DIR` line from your `sdc-env.sh` or `sdcd-env.sh`
- The permission grant you added to `sdc-security.policy`

**Comment by metadaddy** [comment]
Closing this as it's been a couple of weeks now without update. Feel free to reopen if you're still having a problem.
