### ISSUE TITLE
Custom processor Field value getting turncated

### ISSUE THREAD

**Issue by aks1981** [streamsets/tutorials#39]
Hi,

I developed custom processor based on tutorial. Pipline is working good. But when i print JSON value from field its getting truncated json. 
Is any length limit for field.getValueAsString()?

**Below is code:**
	    for (String fieldPath : record.getEscapedFieldPaths()) {
	        Field field = record.get(fieldPath);
	        if (field.getType() == Field.Type.STRING) {
				String json  = field.getValueAsString();
				LOG.info("Field Value::   = " + json);
	        }
	    }

ThankYou,
Ajit

**Comment by metadaddy** [comment]
Hi Ajit,

As far as I can see, if the field value is actually a String,
getValueAsString() will just return toString(), which returns the string
itself. It's possible that LOG.info is doing the truncating. You could
check by logging json.length().

Cheers,

Pat

--

Pat Patterson | Community Champion | http://about.me/patpatterson

**Comment by aks1981** [comment]
Thankyou

**Comment by metadaddy** [comment]
Closing this as there doesn't seem to be a problem in the tutorial. Feel free to reopen if this is not the case.
