### ISSUE TITLE
Is it possible to send error out record in separate pipline while using custom processor

### ISSUE THREAD

**Issue by aks1981** [streamsets/tutorials#41]
Hi,

I am new for StreamSets development.  I implemented custom processor successfully. But I am stuck  with to  send custom processor error records to other destination pipeline.

Thanks,
Ajit

**Comment by metadaddy** [comment]
You can send error records to another pipeline via RPC or Kafka - just set the [Error Records](https://streamsets.com/documentation/datacollector/latest/help/index.html#Pipeline_Configuration/PipelineConfiguration_title.html#task_xlv_jdw_kq) pipeline config and use the appropriate origin in your error handling pipeline with data format **SDC Record**.

Feel free to ask follow-up questions via the Slack channel or Google Group - details at https://streamsets.com/community/
