### ISSUE TITLE
does your solution support k8s or mesos

### ISSUE THREAD

**Issue by wanghaisheng** [streamsets/tutorials#49]
i am currently  evaluating rancher for our internal infrastructure  ,so here comes question 
does streamset support k8s,mesos or rancher such docker container architecture?

**Comment by metadaddy** [comment]
Hi @wanghaisheng - I'm guessing that neither the Google Group or Slack channel work for you. Please email me: pat-at-streamsets-dot-com and we can follow up there. Closing this since it's not an issue in the tutorials.
