### ISSUE TITLE
how to send jobs to spark cluster

### ISSUE THREAD

**Issue by kaige11** [streamsets/tutorials#61]
spark evaluator runs in local, is there any way to send jobs to a spark cluster to execute ? I have a spark cluster managed in standalone mode, how to send jobs to it ? I call setMaster() method to point spark's master to my spark cluster in init method of my spark transformer, but it seems not work .

**Comment by dimaspivak** [comment]
Hi @kaige11, please go through [the Community](https://streamsets.com/community/) for questions about using SDC.
