### ISSUE TITLE
curl -XPUT syntax error

### ISSUE THREAD

**Issue by auddye** [streamsets/tutorials#62]
used the following with a single quote at the end and it worked 

'{
    "mappings": {
        "logs" : {
            "properties" : {
                "timestamp": {"type": "date"},
                "geo": {"type": "geo_point"},
                "city": {
                    "type": "string",
                "index": "not_analyzed"}
            }
        }
    }
}'

**Comment by metadaddy** [comment]
Fixed by ac4f05148b75acd610792aaa7f5697341613aeeb
