### ISSUE TITLE
version 3.0.0 not support kafka 0.8 ?

### ISSUE THREAD

**Issue by sumpan** [streamsets/tutorials#63]
version 3.0.0 not support kafka 0.8 ?

**Comment by sumpan** [comment]
how to install kafka 0.8 plugin ?

**Comment by iwrigley** [comment]
Hi

This isn't really the right place to ask questions like this -- I suggest visiting http://ask.streamsets.com, using the mailing list, or using the community Slack channel. However: Kafka 0.8 is available as a legacy library (really, Kafka 0.8 is very old and has not been recommended for production use for quite some time). For more information, see https://streamsets.com/documentation/datacollector/latest/help/#Installation/AddtionalStageLibs.html#concept_fw3_zt3_tbb

**Comment by sumpan** [comment]
@iwrigley thx a lot
