### ISSUE TITLE
how to define general label for Custom Stage Libraries 

### ISSUE THREAD

**Issue by hwhmusic** [streamsets/tutorials#80]
i follow the tutorials to create my own hbase stage library,  and i want to support different version for 
hbase，i guess i can do it by re-define  the general label,

but  i don't konw how to do that,

**Comment by metadaddy** [comment]
Do you mean you want your custom HBase stage library to be able to support different versions of HBase? This is quite complicated, as you have to use different versions of the HBase client jars. If you look in the main https://github.com/streamsets/datacollector project, we do this by having a hierarchy of Maven projects - for example, with Apache Kudu we have the core code in `kudu-protolib`; each of the `apache-kudu-x_y-lib` projects includes `kudu-protolib` with a different version of the Kudu client jar files.

**Comment by metadaddy** [comment]
Assuming I can close this now, @hwhmusic. Feel to reach out via our [community](https://streamsets.com/community/) if you still need help.
