### ISSUE TITLE
how to load PipelineConfiguration in origin

### ISSUE THREAD

**Issue by ply0011** [streamsets/tutorials#81]
I created a new lib follow the tutorials,then i do something like load schema from the origin database,i wish the data can display on web.But i can't find the way to transform the schema data.

**Comment by metadaddy** [comment]
Hi @ply0011 - what exactly are you trying to do - show the schema data in the StreamSets configuration UI?

**Comment by ply0011** [comment]
@metadaddy yes

**Comment by metadaddy** [comment]
Unfortunately this is not possible at present - please watch/comment/vote on [SDC-6653](https://issues.streamsets.com/browse/SDC-6653).
