### ISSUE TITLE
Not able to find maven dependacies

### ISSUE THREAD

**Issue by rdgandhi** [streamsets/tutorials#89]
Hi I am going through tutorial "Creating a Custom StreamSets Destination", in that two object instances 1) DataGenerator and 2) DelimitedCharDataGenerator could not able to resolved. 

```

import com.streamsets.pipeline.lib.generator.DataGenerator;
import com.streamsets.pipeline.lib.generator.delimited.DelimitedCharDataGenerator;

```
both are not able to resolved.

The mentioned maven repository is not available so adding below mentioned dependency in pom.xml file cause error too,

```
<dependency>
      <groupId>com.streamsets</groupId>
      <artifactId>streamsets-datacollector-commonlib</artifactId>
      <version>1.2.2.0</version>
      <scope>provided</scope>
    </dependency>

```

On maven repository available version is 1.1.3 which is quite older. Your help will be appreciated.
Thanks in advance.

**Comment by metadaddy** [comment]
As mentioned in the tutorial, the destination uses classes from the main datacollector project, so you need to build datacollector from source and install the jars - see https://github.com/streamsets/tutorials/tree/master/tutorial-destination#creating-and-building-a-destination-template

Make sure you have all the prerequisites mentioned in [BUILD.md](https://github.com/streamsets/datacollector/blob/master/BUILD.md).

Feel free to follow up with a comment here if you get stuck!

**Comment by metadaddy** [comment]
Assuming you got it working, @rdgandhi - feel free to reopen this issue if this is not the case.
