### ISSUE TITLE
Pipeline Status: RUN_ERROR: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by SteveBall** [streamsets/tutorials#90]
Hello

I'm trying to follow the spark transformer tutorial but when I come to run my own custom transformer I get class related issues which suggest some sort of config or class path problem but I cannot see how to remedy the situation as the docs suggest when running a pipeline in stand alone mode streamsets will use the built in stage libraries ie I should not have to deploy any dependencies such as xml parsers or spark libs

First run produces the following exception

Pipeline Status: RUN_ERROR: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/type/ReferenceType

whilst a subsequent run produces

Pipeline Status: RUN_ERROR: java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.rdd.RDDOperationScope$

I have followed the readme and used the supplied code and pom file so I'm obviously missing something here 

any thoughts?

thanks

  Steve

**Comment by metadaddy** [comment]
Thanks for reporting this, @SteveBall - it turned out to be a bug in StreamSets Data Collector - [SDC-9884](https://issues.streamsets.com/browse/SDC-9884). This is resolved in Data Collector 3.4.2 and I've updated the tutorials accordingly.
