### ISSUE TITLE
Issue building cdh_6_0-lib subproject

### ISSUE THREAD

**Issue by cupdike** [streamsets/tutorials#92]
Maven CDH downloads for the datacollector build kept hanging until I went in and changed the CDH repo to the following in cdh_6_0-lib/pom.xml: 
````
<!--<url>http://bits.cloudera.com/f93c6c9d/cdh6/6.0.0-beta1/maven-repository/</url>-->
<url>https://repository.cloudera.com/artifactory/cloudera-repos/</url>
````

**Comment by metadaddy** [comment]
That looks like a hangover from the CDH 6 beta. I [created an issue](https://issues.streamsets.com/browse/SDC-9952) - should be fixed soon. Thanks for letting us know!
