### ISSUE TITLE
How can I use JDBC Query Consumer to query data from hive?

### ISSUE THREAD

**Issue by lonelyGhostisdog** [streamsets/tutorials#98]
Hi,i want to  query data from hive by JDBC Query Consumer .But it didn't work .
Error is "JJDBC_00 - Cannot connect to specified database: com.streamsets.pipeline.api.StageException: JDBC_06 - Failed to initialize connection pool: com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization: Method not supported"
How can i solve it?

**Comment by metadaddy** [comment]
Hi @qinzl1 - as the error says, configure a connection test query - see **Legacy Drivers** tab - https://streamsets.com/documentation/datacollector/latest/help/datacollector/UserGuide/Origins/JDBCConsumer.html#task_ryz_tkr_bs

**Comment by metadaddy** [comment]
@lonelyGhostisdog The open source Hive driver does not properly implement the JDBC spec. If you can, download the vendor Hive driver for your distribution - Cloudera/Hortonworks

**Comment by qinzl1** [comment]
@metadaddy Specific which version is valid

**Comment by metadaddy** [comment]
Which distribution are you using?

**Comment by Aditya-dixit** [comment]
Worked for me once I switched to cloudera hive jdbc driver jar. 
As @metadaddy rightly mentioned, open source hive driver doesn't implement all the methods needed by streamsets for making JDBC connection.

**Comment by metadaddy** [comment]
@lonelyGhostisdog / @qinzl1 Did you get this working? Can I close the issue?

**Comment by qinzl1** [comment]
@metadaddy 
it seem hive jdbc not only need configuration jdbc url ，but need hive-site.xml and hadoop config file. and JDBC origins stage didn't have Configuration items

**Comment by metadaddy** [comment]
@qinzl1 Use the Cloudera driver from https://www.cloudera.com/documentation/other/connectors/hive-jdbc/latest.html

**Comment by metadaddy** [comment]
Closing this since it's not actually an issue in the tutorials. Feel free to engage further via the StreamSets community https://streamsets.com/community/
